### ISSUE TITLE
Context atlas: Coloring and labeling is different across browsers

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/interpretability#10]
This may be related to https://github.com/PAIR-code/interpretability/pull/5, but I noticed that the coloring and labeling is different in Firefox vs. Chrome/Safari.  I'd guess this might have an impact on how people perceive the visualization, so thought it was worth sharing, but I didn't look further and just switched to Safari :)

Here are two examples:

### "fair" firefox
<img width="1284" alt="Screen Shot 2019-08-21 at 2 19 23 PM" src="https://user-images.githubusercontent.com/1056957/63457534-3bee1600-c41f-11e9-96bf-c6c8529d9126.png">

### "fair" in safari
<img width="1275" alt="Screen Shot 2019-08-21 at 2 19 38 PM" src="https://user-images.githubusercontent.com/1056957/63457548-41e3f700-c41f-11e9-8c3f-8354230132b5.png">

## "lie" in firefox
<img width="1287" alt="Screen Shot 2019-08-21 at 2 20 11 PM" src="https://user-images.githubusercontent.com/1056957/63457519-35f83500-c41f-11e9-8c91-a4e03c22c779.png">

## "lie" in safari
<img width="1270" alt="Screen Shot 2019-08-21 at 2 20 03 PM" src="https://user-images.githubusercontent.com/1056957/63457700-7b1c6700-c41f-11e9-8c0c-7fb410f4ff27.png">

**Comment by 1wheel** [comment]
Gross.

 Easier way to fix will probably be [estimating](https://github.com/gka/d3-jetpack/blob/master/src/wordwrap.js#L6-L10) the bounding box size based on the string/size and checking for intersections in js without using DOM APIs.

**Comment by kevinrobinson** [comment]
I think this is just my bug from the polyfill, https://github.com/PAIR-code/interpretability/pull/12 should help out.

**Comment by EmilyReif** [comment]
Yup, thanks @kevinrobinson! Looks good now
