### ISSUE TITLE
Error from deploy.sh

### ISSUE THREAD

**Issue by scarletcho** [PAIR-code/interpretability#27]
I'm trying to deploy my own data to Context Atlas visualization and I'm getting an error message as follows:

> "ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object."

May I ask how to solve this issue?

**Comment by iislucas** [comment]
I think @1wheel will know ... ?

**Comment by 1wheel** [comment]
https://github.com/PAIR-code/interpretability/blob/master/context-atlas/deploy.sh is hard coded to upload to `gs://bert-wsd-vis` — you'd need to fork and point it at a bucket you control.
