### ISSUE TITLE
download scripts wants the dir to exist

### ISSUE THREAD

**Issue by arnicas** [PAIR-code/interpretability#7]
It looks like the script download_pregenerated_jsons.sh wants the static/jsons folder to exist? 

Also, tiny nit in the Readme - you might want to warn people how much data they are about to download. Eek.
-Lynn

**Comment by kevinrobinson** [comment]
I ran into this too - fwiw
https://github.com/PAIR-code/interpretability/pull/6 adds a mkdir -p which
should do the trick, although it sounds like you might have already figured
that out :)

**Comment by EmilyReif** [comment]
Ah, yup, thanks to @kevinrobinson, should be fixed now! 

And good call, I'll add a note :)
